#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
##  file: /var/log/tomcat/sell.log
##  level:
##    com.wanwujinhua.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.14/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxa5c8f272d562936f
  mpAppSecret: 902e84e91ddc48566731107bb568ce99
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://pdpnat.natapp1.cc/sell/pay/notify
