#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
##  file: /var/log/tomcat/sell.log
##  level:
##    com.wanwujinhua.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.14/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
